---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  workflows:
    uses: baggier-rasa/addon-pocket-id/.github/workflows/release-drafter.yaml@main
